Create Readable Documentation
cda-tum/ddsim pull request #39
Opened 2022-02-24 14:20 UTC by hillmich

- Streamline README.md
- Put elaborate documentation on ReadTheDocs

2022-03-02 15:23 UTC, burgholzer requested changes
As expected, the most critical comments are targeting the README.
The other stuff should be easy to incorporate.

2022-03-02 15:23 UTC, burgholzer commented on docs/source/index.rst
> +If you have any questions, feel free to contact us via iic-quantum@jku.at or by creating an issue on GitHub.
Add hyperlinks here?

2022-03-02 15:23 UTC, burgholzer commented on docs/source/refs.bib
> +  title     = {As Accurate as Needed, as Efficient as Possible: Approximations in DD-based Quantum Circuit Simulation},
```suggestion
  title     = {As Accurate as Needed, as Efficient as Possible: {A}pproximations in {DD}-based Quantum Circuit Simulation},
```

2022-03-02 15:23 UTC, burgholzer commented on docs/source/refs.bib
> +}
No newline at end of file

2022-03-02 15:23 UTC, burgholzer commented on docs/source/refs.bib
> +@misc{burgholzer2021hybrid,
wrong entry type

2022-03-02 15:23 UTC, burgholzer commented on docs/source/simulators/CircuitSimulator.rst
> +If you are using this simulator, please cite :cite:p:`zulehner2019advanced`.
Theoretically one should cite the QCE21 paper if the hybrid SchrodingerFeynman stuff is used. It's unfortunate that there is no extra section on the hybrid simulator. Should we add one?

2022-03-02 15:23 UTC, burgholzer commented on docs/source/simulators/SimulationPathFramework.rst
> +    [...]
why is this here?

2022-03-03 12:14 UTC, hillmich commented on docs/README.md
> +For more information, on our work on quantum circuit simulation please visit [iic.jku.at/eda/research/quantum_simulation](https://iic.jku.at/eda/research/quantum_simulation) or, for more information
Safety copy ^^

2022-03-03 12:29 UTC, hillmich commented on docs/source/simulators/SimulationPathFramework.rst
> +    [...]
Oversight on my end.

2022-03-03 13:22 UTC, hillmich commented on README.md
>  [![Language grade: C/C++](https://img.shields.io/lgtm/grade/cpp/github/cda-tum/ddsim?label=c%2B%2B&logo=lgtm)](https://lgtm.com/projects/g/cda-tum/ddsim/context:cpp)
I'd keep the single line of badges at the top, that seems to be a nice way to avoid an excessive number of badges.

2022-03-03 13:28 UTC, hillmich commented on README.md
>  print(circ.draw(fold=-1))
I think it's nice for example to show the circuit alongside the counts.

2022-03-03 13:35 UTC, hillmich commented on README.md
> +The simulator builds upon [our quantum functionality representation (QFR)](https://github.com/cda-tum/qfr.git) which in turns builds on [our decision diagram (DD) package](https://github.com/cda-tum/
I'd keep the sentence since showing the connection to our other projects has value if want people to perceive the tools as somewhat connected.

2022-03-03 17:59 UTC, burgholzer approved these changes

2022-03-03 18:00 UTC, merged